version: 0.0
os: linux

files:
  - source: index.html
    destination: /var/www/html
    overwrite: true
  - source: deploy-info.json
    destination: /var/www/html
    overwrite: true

permissions:
  - object: /var/www/html
    pattern: "**"
    owner: root
    group: root

hooks:
  BeforeInstall:
    - location: scripts/before_install.sh
      timeout: 300
      runas: root
  AfterInstall:
    - location: scripts/restart_httpd.sh
      timeout: 120
      runas: root
